# Base settings for the Resync application (compatible with Dynaconf)
# This file contains default values from the original Settings class

[default]
# Project Metadata
PROJECT_NAME = "Resync"
PROJECT_VERSION = "1.0.0"
DESCRIPTION = "Real-time monitoring dashboard for HCL Workload Automation"
# BASE_DIR is dynamically determined based on the current working directory
# This allows the application to work in different environments (local, CI/CD, container)

# Agent and Model Configuration
AGENT_CONFIG_PATH = "config/runtime.json"
LLM_MODEL_PATH = "models/Meta-Llama-3-8B-Instruct.Q4_K_M.gguf"
LLM_ENDPOINT = "http://localhost:8001/v1"
LLM_API_KEY = "your_default_api_key_here"
AUDITOR_MODEL_NAME = "gpt-4o-mini"
LLM_N_GPU_LAYERS = -1

# Knowledge Graph (Mem0) Configuration
MEM0_EMBEDDING_PROVIDER = "openai"
MEM0_EMBEDDING_MODEL = "text-embedding-3-small"
MEM0_LLM_PROVIDER = "openai"
MEM0_LLM_MODEL = "gpt-4o-mini"
MEM0_STORAGE_PROVIDER = "qdrant"
MEM0_STORAGE_HOST = "localhost"
MEM0_STORAGE_PORT = 6333

# Neo4j Knowledge Graph Configuration (para desenvolvimento)
NEO4J_URI = "bolt://localhost:7687"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "password"

# Redis Configuration
REDIS_URL = "redis://localhost:6379"

# TWS Environment Configuration
TWS_MOCK_MODE = false
TWS_CACHE_TTL = 60

# Cache Hierarchy Configuration
CACHE_HIERARCHY_L1_MAX_SIZE = 5000
CACHE_HIERARCHY_L2_TTL = 600
CACHE_HIERARCHY_L2_CLEANUP_INTERVAL = 60
CACHE_HIERARCHY_NUM_SHARDS = 8
CACHE_HIERARCHY_MAX_WORKERS = 4
ASYNC_CACHE_CONCURRENCY_THRESHOLD = 5

# Async Cache Configuration
ASYNC_CACHE_TTL = 60
ASYNC_CACHE_CLEANUP_INTERVAL = 30
ASYNC_CACHE_NUM_SHARDS = 8
ASYNC_CACHE_MAX_WORKERS = 4

# KeyLock Configuration
KEY_LOCK_MAX_LOCKS = 2048

# TWS Credentials (must be set via environment variables)
TWS_HOST = ""
TWS_PORT = 31111
TWS_USER = ""
TWS_PASSWORD = ""
TWS_ENGINE_NAME = "tws-engine"
TWS_ENGINE_OWNER = "tws-owner"

# Logging Configuration
LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_FILE_PATH = "logs/resync.log"

# RAG (Retrieval-Augmented Generation) Configuration
RAG_DIR = "rag"

# File Processing Configuration
PROTECTED_DIRECTORIES = ["resync", "config", "templates", "static"]
KNOWLEDGE_BASE_DIRS = ["resync/RAG"]

# Application Environment (default to development)
APP_ENV = "development"

# Content Security Policy (CSP) Configuration
CSP_ENABLED = true
CSP_REPORT_ONLY = false
CSP_REPORT_URI = "/csp-violation-report"

# Rate Limiting Configuration
RATE_LIMIT_PUBLIC_PER_MINUTE = 100
RATE_LIMIT_AUTHENTICATED_PER_MINUTE = 1000
RATE_LIMIT_CRITICAL_PER_MINUTE = 50
RATE_LIMIT_ERROR_HANDLER_PER_MINUTE = 15
RATE_LIMIT_WEBSOCKET_PER_MINUTE = 30
RATE_LIMIT_DASHBOARD_PER_MINUTE = 10
RATE_LIMIT_STORAGE_URI = "redis://localhost:6379"
RATE_LIMIT_KEY_PREFIX = "resync:ratelimit:"
RATE_LIMIT_SLIDING_WINDOW = true

# Connection Pool Configuration
# Database Connection Pool Settings
DB_POOL_MIN_SIZE = 5
DB_POOL_MAX_SIZE = 20
DB_POOL_TIMEOUT = 30
DB_POOL_RETRY_ATTEMPTS = 3
DB_POOL_RETRY_DELAY = 1
DB_POOL_HEALTH_CHECK_INTERVAL = 60
DB_POOL_IDLE_TIMEOUT = 300

# Redis Connection Pool Settings
REDIS_POOL_MIN_SIZE = 5
REDIS_POOL_MAX_SIZE = 20
REDIS_POOL_TIMEOUT = 30
REDIS_POOL_RETRY_ATTEMPTS = 3
REDIS_POOL_RETRY_DELAY = 1
REDIS_POOL_HEALTH_CHECK_INTERVAL = 60
REDIS_POOL_IDLE_TIMEOUT = 300

# HTTP/TWS Connection Pool Settings
TWS_CONNECT_TIMEOUT = 10
TWS_READ_TIMEOUT = 30
TWS_WRITE_TIMEOUT = 30
TWS_POOL_TIMEOUT = 30
TWS_MAX_CONNECTIONS = 100
TWS_MAX_KEEPALIVE = 20
TWS_POOL_RETRY_ATTEMPTS = 3
TWS_POOL_RETRY_DELAY = 1

# WebSocket Connection Pool Settings
WS_POOL_MAX_SIZE = 1000
WS_POOL_CLEANUP_INTERVAL = 60
WS_CONNECTION_TIMEOUT = 30

# Health Check Configuration
HEALTH_CHECK_ENABLED = true
HEALTH_CHECK_INTERVAL = 60
HEALTH_CHECK_TIMEOUT = 30
HEALTH_CHECK_ALERTS_ENABLED = true
HEALTH_CHECK_DB_TIMEOUT = 10
HEALTH_CHECK_REDIS_TIMEOUT = 5
HEALTH_CHECK_EXTERNAL_API_TIMEOUT = 15
HEALTH_CHECK_FILE_SYSTEM_THRESHOLD = 90.0
HEALTH_CHECK_MEMORY_THRESHOLD = 85.0
HEALTH_CHECK_CPU_THRESHOLD = 80.0
HEALTH_CHECK_ALERT_THRESHOLD_DEGRADED = 1
HEALTH_CHECK_ALERT_THRESHOLD_UNHEALTHY = 1
HEALTH_CHECK_ALERT_COOLDOWN = 300
HEALTH_CHECK_HISTORY_RETENTION_HOURS = 24
HEALTH_CHECK_MAX_HISTORY_ENTRIES = 1000
HEALTH_CHECK_HISTORY_CLEANUP_THRESHOLD = 0.8
HEALTH_CHECK_HISTORY_CLEANUP_BATCH_SIZE = 100
HEALTH_CHECK_ENABLE_MEMORY_MONITORING = true
HEALTH_CHECK_MEMORY_USAGE_THRESHOLD_MB = 50
HEALTH_CHECK_HISTORY_COMPRESSION_ENABLED = false
HEALTH_CHECK_HISTORY_RETENTION_DAYS = 7