# Resync Application Settings
# This file contains the base configuration for the Resync application.

[default]
# --- Project Metadata ---
PROJECT_NAME = "Resync"
PROJECT_VERSION = "1.0.0"
DESCRIPTION = "Real-time monitoring dashboard for HCL Workload Automation"

# --- Base Directory ---
# Automatically determined based on current working directory
# This allows the application to work in different environments (local, CI/CD, container)
BASE_DIR = "."  # Will be resolved to absolute path at runtime

# --- Neo4j Configuration ---
NEO4J_URI = "bolt://localhost:7687"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "password"

# --- Redis Configuration ---
REDIS_URL = "redis://localhost:6379"

# --- Language Model Configuration ---
LLM_ENDPOINT = "http://localhost:11434/v1"
LLM_API_KEY = "your_default_api_key_here"  # Replace with actual API key
LLM_MODEL_NAME = "llama3"
LLM_TEMPERATURE = 0.1

# --- Admin Credentials ---
# These must be explicitly set for security - no insecure defaults in production
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"

# --- TWS Environment Configuration ---
# TWS credentials are only required if not in mock mode
TWS_MOCK_MODE = false
TWS_HOST = "localhost"
TWS_PORT = 31111
TWS_USER = "twsuser"
TWS_PASSWORD = "twspassword"
TWS_ENGINE_NAME = "tws-engine"
TWS_ENGINE_OWNER = "tws-owner"

# --- Microsoft Teams Integration ---
[default.TEAMS_INTEGRATION]
enabled = false
webhook_url = ""  # Teams incoming webhook URL
channel_name = "Resync Notifications"
bot_name = "Resync Bot"
avatar_url = ""  # Optional avatar image URL
enable_conversation_learning = false
enable_job_notifications = false
monitored_tws_instances = []  # List of TWS instance names to monitor
job_status_filters = ["ABEND", "ERROR", "FAILED"]  # Job statuses that trigger notifications
notification_types = ["job_status", "alerts", "performance"]

# --- Cache Hierarchy Configuration ---
[default.CACHE_HIERARCHY]
L1_MAX_SIZE = 5000
L2_TTL_SECONDS = 600
L2_CLEANUP_INTERVAL = 60
NUM_SHARDS = 8
MAX_WORKERS = 4

# --- Async Cache Configuration ---
[default.ASYNC_CACHE]
TTL_SECONDS = 60
CLEANUP_INTERVAL = 30
NUM_SHARDS = 8
MAX_WORKERS = 4

# --- KeyLock Configuration ---
[default.KEYLOCK]
MAX_LOCKS = 2048

# --- Connection Pool Configuration ---
[default.CONNECTION_POOL]
# Database Connection Pool Settings
DB_POOL_MIN_SIZE = 5
DB_POOL_MAX_SIZE = 20
DB_POOL_TIMEOUT = 30
DB_POOL_RETRY_ATTEMPTS = 3
DB_POOL_RETRY_DELAY = 1
DB_POOL_HEALTH_CHECK_INTERVAL = 60
DB_POOL_IDLE_TIMEOUT = 300

# Redis Connection Pool Settings
REDIS_POOL_MIN_SIZE = 5
REDIS_POOL_MAX_SIZE = 20
REDIS_POOL_TIMEOUT = 30
REDIS_POOL_RETRY_ATTEMPTS = 3
REDIS_POOL_RETRY_DELAY = 1
REDIS_POOL_HEALTH_CHECK_INTERVAL = 60
REDIS_POOL_IDLE_TIMEOUT = 300

# HTTP/TWS Connection Pool Settings
TWS_CONNECT_TIMEOUT = 10
TWS_READ_TIMEOUT = 30
TWS_WRITE_TIMEOUT = 30
TWS_POOL_TIMEOUT = 30
TWS_MAX_CONNECTIONS = 100
TWS_MAX_KEEPALIVE = 20
TWS_POOL_RETRY_ATTEMPTS = 3
TWS_POOL_RETRY_DELAY = 1

# WebSocket Connection Pool Settings
WS_POOL_MAX_SIZE = 1000
WS_POOL_CLEANUP_INTERVAL = 60
WS_CONNECTION_TIMEOUT = 30

# --- Rate Limiting Configuration ---
[default.RATE_LIMITING]
PUBLIC_REQUESTS_PER_MINUTE = 100
AUTHENTICATED_REQUESTS_PER_MINUTE = 1000
CRITICAL_REQUESTS_PER_MINUTE = 50
ERROR_HANDLER_REQUESTS_PER_MINUTE = 15
WEBSOCKET_REQUESTS_PER_MINUTE = 30
DASHBOARD_REQUESTS_PER_MINUTE = 10
STORAGE_URI = "redis://localhost:6379"
KEY_PREFIX = "resync:ratelimit:"
SLIDING_WINDOW = true

# --- Health Check Configuration ---
[default.HEALTH_CHECK]
ENABLED = true
INTERVAL_SECONDS = 60
TIMEOUT_SECONDS = 30
ALERTS_ENABLED = true
DB_TIMEOUT_SECONDS = 10
REDIS_TIMEOUT_SECONDS = 5
EXTERNAL_API_TIMEOUT_SECONDS = 15
FILE_SYSTEM_THRESHOLD_PERCENT = 90.0
MEMORY_THRESHOLD_PERCENT = 85.0
CPU_THRESHOLD_PERCENT = 80.0
ALERT_THRESHOLD_DEGRADED = 1
ALERT_THRESHOLD_UNHEALTHY = 1
ALERT_COOLDOWN_SECONDS = 300
HISTORY_RETENTION_HOURS = 24
MAX_HISTORY_ENTRIES = 1000
HISTORY_CLEANUP_THRESHOLD = 0.8
HISTORY_CLEANUP_BATCH_SIZE = 100
HISTORY_COMPRESSION_ENABLED = false
HISTORY_RETENTION_DAYS = 7
ENABLE_MEMORY_MONITORING = true
MEMORY_USAGE_THRESHOLD_MB = 50
MEMORY_HISTORY_RETENTION_HOURS = 24
HISTORY_CLEANUP_THRESHOLD_PERCENT = 0.8

# --- Logging Configuration ---
[default.LOGGING]
LEVEL = "INFO"
FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
FILE_PATH = "logs/resync.log"

# --- RAG (Retrieval-Augmented Generation) Configuration ---
[default.RAG]
DIRECTORY = "rag"
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200

# --- File Processing Configuration ---
[default.FILE_PROCESSING]
PROTECTED_DIRECTORIES = ["resync", "config", "templates", "static"]
KNOWLEDGE_BASE_DIRECTORIES = ["resync/RAG"]

# --- Application Environment ---
[default.APPLICATION]
ENV = "development"
DEBUG = false

# --- Content Security Policy (CSP) Configuration ---
[default.CSP]
ENABLED = true
REPORT_ONLY = false
REPORT_URI = "/csp-violation-report"

# --- CORS Configuration ---
[default.CORS]
ENABLED = true
ALLOWED_ORIGINS = ["http://localhost:3000", "http://localhost:8000"]
ALLOW_CREDENTIALS = false
LOG_VIOLATIONS = true

# --- Development Environment Overrides ---
[development]
DEBUG = true
TWS_MOCK_MODE = true
LOGGING.LEVEL = "DEBUG"

# --- Production Environment Overrides ---
[production]
DEBUG = false
TWS_MOCK_MODE = false
LOGGING.LEVEL = "INFO"

# --- Test Environment Overrides ---
[test]
DEBUG = true
TWS_MOCK_MODE = true
LOGGING.LEVEL = "DEBUG"