# Development-specific overrides for Dynaconf
# These values override the defaults in settings.toml for development environment

[default]
APP_ENV = "development"
# TWS Configuration for Development
TWS_MOCK_MODE = true
TWS_VERIFY_SSL = false  # SSL verification disabled for development

# Cache Hierarchy Settings for Development
CACHE_HIERARCHY_L1_MAX_SIZE = 1000  # Smaller for quick testing
CACHE_HIERARCHY_L2_TTL = 300  # Shorter TTL for dev
CACHE_HIERARCHY_L2_CLEANUP_INTERVAL = 30
CACHE_HIERARCHY_NUM_SHARDS = 8
CACHE_HIERARCHY_MAX_WORKERS = 4

# Optional LLM Endpoint for Development
# LLM_ENDPOINT = "http://localhost:8001/v1"
